pipeline {
    agent any
    tools {
        maven 'Maven 3.6.1' 
    }
    stages {
        stage('build') { 
            steps {
                echo 'Compiling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test') { 
            steps {
                echo 'Running unit Tests on worker app'
                
            }
        }
        stage('package') { 
            steps {
                echo 'packging worker app'
                
            }
        }
        
    }
    post { 
        always { 
            echo 'Build pipeine for worker is complete..'
        }
    }
}
